### ISSUE TITLE
Neue Portalräume - Stuck in connector

### ISSUE THREAD

**Issue by 2peter3** [derjp/griefergames#2]
Hi,
ich war gerade dabei für den neuen Portalraum die Path Dateien anzulegen.
Jedoch stoße ich auf einen Fehler:

`
[GrieferGames] Du bist im Portalraum. Wähle deinen Citybuild aus.
Error: Stuck in connector.
    at Object.<anonymous> (/Users/karl/dev/testing/test/griefergames/dist/tasks/connector.js:143:27)
    at step (/Users/karl/dev/testing/test/griefergames/dist/tasks/connector.js:33:23)
    at Object.throw (/Users/karl/dev/testing/test/griefergames/dist/tasks/connector.js:14:53)
    at rejected (/Users/karl/dev/testing/test/griefergames/dist/tasks/connector.js:6:65)
/Users/karl/dev/testing/test/griefergames/dist/tasks/connector.js:71
                        throw new Error('Timed out while connecting on CityBuild.');
                        ^

Error: Timed out while connecting on CityBuild.
    at Timeout._onTimeout (/Users/karl/dev/testing/test/griefergames/dist/tasks/connector.js:71:31)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

`

cb5.json:
`
{
  "name": "cb5",
  "start": 0,
  "front": [310, 116, 284],
  "portal": [311, 116, 284]
}
`

Vielleicht hat jemand einen kurzen Hinweis

mfg Karl

**Comment by derjp** [comment]
Hey,

danke für dein Interesse. :) Ich habe an dem Projekt ziemlich lange nicht mehr gearbeitet. Spontan kann ich dir aber sagen, dass der neue Portalraum ziemlich sicher ein/das Problem ist.

Siehe: https://github.com/derjp/griefergames/blob/master/paths/

Die Koordinaten hab ich vor 10 Monaten definiert, das heißt, alle Server ab CB12 werden nicht unterstützt (es sind schlichtweg keine Koordinaten definiert) und alle Koordinaten sind falsch, weil der Portalraum komplett erneuert worden ist (die Portale stehen jetzt an verschiedenen Stellen, der Weg müsste vermutlich auch geändert werden).

Gib mir bitte zurück, ob du noch Interesse an dieser Library hast. Wenn ja, dann würde ich es für die neuen CityBuild-Server updaten und alle Koordinaten erneuern, sobald ich Zeit habe. Hab aber bitte Verständnis, dass es etwas dauern könnte, bis ich dazu komme.

Entschuldige übrigens die späte Rückmeldung, ich hab meine Benachrichtigungen jetzt hoffentlich gefixt.

Liebe Grüße
DerJP

**Comment by 2peter3** [comment]
Hi DerJP,
erstmal sorry für die lange Inaktivität. Ich versuche nun schon zwei Tage die Koordinaten anzupassen, für den neuen Portalraum. Das Problem ist jedoch der "Teppich" in dem Raum. Vielleicht hast du hier einen kleinen Tipp? 

Danke vorab ;-)

**Comment by derjp** [comment]
Hey,

ich schaue es mir heute an.

LG!

**Comment by derjp** [comment]
Hey nochmal,

der neue Portalraum ist vom Aufbau wirklich sehr ungünstig... Ich hab mich am Montag drangesetzt es zu fixen, kann aber diesmal nicht die Physik-Implementation mit ein paar Tricks kompensieren. Ich weiß ehrlich gesagt nicht, wie ich das lösen soll. Ich habe in der Vergangenheit schon probiert, die Packets eines Weges aufzunehmen und dann bei Aufruf von .connectCityBuild wie eine Aufnahme abzuspielen, was aber aufgrund der AntiCheat-Software von GrieferGames nicht funktioniert hat.
Mir fehlt in dem Bereich einfach die Erfahrung mit Minecraft-Serversoftware, der Software von GrieferGames und Programmierung auf low level, wie in dem Fall mit Packets.

Ich sehe momentan keine Lösung. Wenn du eine Idee hast und dich an die Lösung setzen magst, zöger nicht zum „update-connector“-Branch zu commiten! Würde mich freuen.

https://github.com/derjp/griefergames/tree/update-connector

Grüße,
DerJP

**Comment by Dominic11** [comment]
Das Problem, dass mineflayer-navigate Teppiche als ganze Blöcke sieht, habe ich vor Kurzem damit gelöst, dass ich in der Datei "node_modules/minecraft-data/minecraft-data/data/pc/1.8/blocks.json" beim Teppich (ID: 171) den Wert "boundingBox" von "block" auf "empty" geändert habe. So sieht mineflayer die Teppiche als nicht volle Blöcke und läuft durch sie hindurch wie z. B. bei Bannern oder Schildern. Diese Lösung ist zwar nicht optimal, weil die Datei durch NPM wieder überschrieben wird und man die Änderung für jeder Minecraft Version vornehmen muss, aber sie sollte fürs Erste funktionieren. Für Slabs habe ich es noch nicht getestet, es sollte aber auch dafür funktionieren.

**Comment by derjp** [comment]
Das wird aber vom AntiCheat geflaggt, oder nicht? Im Grunde fliegt er nach dieser Änderung zwar nicht mehr, aber versucht sich durch Blöcke hindurch zu bewegen. So war zumindest meine Erfahrung damit, als ich es früher probiert hab.

**Comment by Dominic11** [comment]
Ich hatte es gestern ausprobiert und der Spieler konnte über Teppiche gehen, für Slabs funktioniert es jedoch nicht weil sie wahrscheinlich zu hoch sind und deshalb das AntiCheat den Spieler zurückteleportiert.

Gibt es eine Möglichkeit mit einem 2. Account in den gleichen Portalraum zu kommen wie der Spieler, der von mineflayer gesteuert wird? Das würde das Testen um einiges vereinfachen, da man den Bot dann beobachten könnte.

**Comment by derjp** [comment]
> Gibt es eine Möglichkeit mit einem 2. Account in den gleichen Portalraum zu kommen wie der Spieler, der von mineflayer gesteuert wird? Das würde das Testen um einiges vereinfachen, da man den Bot dann beobachten könnte.

Man muss sich in den selben Portalraum brute-forcen, also zeitgleich mit dem Bot in den Portalraum gehen und hoffen, dass GrieferGames euch beide in den selben Portalraum schiebt. Früher war das noch relativ einfach (es gab nur drei Portalräume), mittlerweile gibt es aber 9(?), was es wirklich schwierig macht. 😄

**Comment by derjp** [comment]
Hey, der Bot sollte jetzt mit dem neusten Update wieder auf CityBuilds verbinden können. Wir haben außerdem Koordinaten für alle CityBuilds hinzugefügt, man müsste nun problemlos auf jeden CityBuild kommen.

Es muss allerdings noch manuell in der Datei "/node_modules/minecraft-data/minecraft-data/data/pc/1.8/blocks.json" bei den IDs 90 (portal) und 171 (carpet) der boundingBox-Eintrag auf "empty" geändert werden.

**Comment by Dominic11** [comment]
Funktioniert leider noch immer nicht richtig. Der Bot ist bei ca. 80 % meiner Tests im Portalraum entweder bei den Teppichen am Spawn (wie auf dem Screenshot zu sehen ist) oder bei den Stufen vor den Portalen hängen geblieben. Der Bot ist aber inzwischen schon gut benutzbar, wenn man in einer Schleife mehrmals versucht, sich auf einen CityBuild zu verbinden.

![2020-02-25_13 31 43](https://user-images.githubusercontent.com/51837582/75248662-d8c9ab80-57d4-11ea-9540-4eab4228e4a5.png)

**Comment by derjp** [comment]
Eigentlich sollte er nicht an Teppichen hängenbleiben können, wenn du im minecraft-data package die boundingBox von carpets auf empty gesetzt hast. Ist das so bei dir eingestellt?

**Comment by Dominic11** [comment]
Ich habe die Einträge nochmal überprüft und boundingBox steht bei Portalen und Teppichen auf empty. So wie der Bot aber versucht in der Luft zu laufen kommt es mir auch so vor als wären die 2 Einträge nicht berücksichtigt worden.

**Comment by Dominic11** [comment]
Habe alle Module noch mal neu installiert und die Änderungen in der blocks.json Datei vorgenommen und jetzt funktioniert der Bot einwandfrei.
Es treten nur noch Probleme auf, wenn man den Bot in kurzer Zeit oft den CB wechseln lässt. (Wahrscheinlich weil das AntiCheat ihn nach mehreren "cheat Versuchen" öfter flaggt). Dies ist aber bei den meisten Anwendungen für einen Bot nicht nötig und lässt sich beheben in dem man zwischendurch mit einem normalen MC-Client den Server betritt.

**Comment by derjp** [comment]
Kommt eine Fehlermeldung? In welcher Form tritt der Fehler auf, was passiert genau?

So ganz ohne Ahnung kann ich nur die folgenden Schritte vorschlagen:

- Es ist sehr zu empfehlen "cacheSessions: true" zu den Optionen beim Erstellen des Bots hinzuzufügen, dann wird die Session des Accounts zwischengespeichert und bei Bedarf automatisch erneuert. Dadurch vermeidet man, dass Mojang einen nach zu vielen Anmeldungen temporär sperrt (ohne die Option wird bei jeder Verbindung zum Server eine neue Session angefordert). Ich sollte das vermutlich als default setzen und nicht nur optional machen... 🙃 -- Vielleicht ist das der Fehler bei dir?

**Comment by Dominic11** [comment]
Das Problem, dass ich von Mojang gesperrt werde hatte ich beim Testen auch habe aber dann einfach gewartet. Jetzt mit "cacheSessions: true" tritt es gar nicht mehr auf.
Eher problematisch ist es das richtige Portal zu finden. Manchmal funktioniert es sehr gut, da findet der Bot 3-mal hintereinander den richtigen CB. Und manchmal kommt bei jedem Versuch die Fehlermeldung

> Error: Stuck in connector.

und dann

> Error: Timed out while connecting on CityBuild.

Was ja bedeutet, dass der Bot das Portal nicht erreichen konnte, er steht dann meistens an der Stelle, wie auf dem Screenshot von gestern zu sehen ist.

Ich habe den Bot bis jetzt an CB extreme getestet, da er später auch auf diesem CB sein soll.

**Comment by derjp** [comment]
Ich hab gestern noch eine kleine Änderung vorgenommen, wodurch der Bot nun deutlich häufiger verbinden kann. :) Die Portale im neuen Portalraum sind so eingestellt, dass nur das mittlere Stück des Portals den Spieler teleportiert. Die Teile links und rechts davon machen gar nichts, man kann einfach in ihnen stehen und wird nicht teleportiert. Der Bot hat früher oft in den Ecken verfangen, da er nun aber im Portal hin und her läuft, kommt er immer in die Mitte.

> Error: Stuck in connector.

Tritt leider auf, wenn der Bot es nicht schafft eine bestimmte Strecke zu laufen (hängt vermutlich mit Lags zusammen). Woran es genau liegt, kann ich nicht genau sagen, der Fehler wird geworfen wenn mineflayer einen (sehr kryptischen) Fehler zurückgibt. Da der Fehler bei meinen Tests sehr selten auftritt, sollte er hoffentlich verkraftbar sein.

> Error: Timed out while connecting on CityBuild.

Der Fehler wird geworfen, wenn der Bot es nicht schafft in der vorgegeben Zeit (durch meine Library festgelegt) auf den CityBuild zu connecten. Dieser Fehler sollte mit dem neuen Update allerdings deutlich seltener auftreten als früher, weil sich der Bot eigentlich nur in den Ecken der Portale aufgehangen hat.

**Comment by Dominic11** [comment]
Habe den Bot noch mal getestet und er scheint momentan recht gut zu funktionieren. Er findet das Portal zwar immer noch nicht bei jedem Versuch, aber deutlich öfter als vorher.
